### ISSUE TITLE
Sampled maximum molecule size is negative with high probability

### ISSUE THREAD

**Issue by alstonlo** [AustinT/mol_ga#15]
Hi @AustinT, thanks for the nice package! 

I noticed that a default `std_num_atoms=1e3` was set in the [`mol_ok()` function](https://github.com/AustinT/mol_ga/blob/078ef5e555a4bdd092614b402817fefc8602beac/mol_ga/graph_ga/crossover.py#L74-L89), which from the README, I understand as being chosen to provide a generous upper-limit to the molecule size. However, since the target size is drawn from a Gaussian, there is a ~50% chance that the sampled target size is negative, which will cause `mol_ok()` to fail on all inputs. This is probably inconsequential to the performance of the GA, but it might cause the crossover and mutation operations to be a bit more expensive than they have to be. 

One solution could be to draw from a half-normal distribution.

**Comment by AustinT** [comment]
Thanks @alstonlo, you're obviously right- I don't know why this didn't occur to me when I modified that line of the original graph GA algorithm 😮 

I will look into this and most likely push an updated version of the package which fixes this. Thanks for pointing this out!

**Comment by alstonlo** [comment]
Thanks! Feel free to close this PR too!

**Comment by AustinT** [comment]
Fixed in #16, so I'll close this issue. I just published v0.2.1 so that the changes are reflected on PyPI. Thanks again @alstonlo !
